language: python
python:
        - "3.6"
install:
        - pip install -r requirements/ci.txt
script:
        - coverage run manage.py test
        - coverage report
        - coverage xml
        - codecov --file coverage/coverage.xml
